package models

import "time"

type Invoice struct {
	AccessNumber       string   `json:"custbody_access_number"`
	Serial             string   `json:"custbody_diag_invoice_serial"`
	Form               string   `json:"custbody_diag_invoice_form"`
	InvoiceNo          *uint32  `json:"custbody_diag_invoice_no"`
	IssueDate          *string  `json:"custbody_diag_invoice_date"`
	InvoiceAmt         *float64 `json:"custbody_4"`
	ReservationCode    *string  `json:"custbody_7"`
	AdjustNo           *uint32  `json:"custbody_9"`
	AdjustDate         *string  `json:"custbody_diag_invoice_adj_date"`
	AdjInvoiceAmt      *float64 `json:"custbody_diag_invadj_amt"`
	AdjustmentType     *string  `json:"custbody_diag_invoice_adjtype"`
	AdjReservationCode *string  `json:"custbody_vat_lookup_code_adj"`
}

type InvoiceResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    struct {
		Content []struct {
			ID                        int       `json:"id"`
			State                     int       `json:"state"`
			CreatedBy                 string    `json:"createdBy"`
			CreatedDate               time.Time `json:"createdDate"`
			LastModifiedBy            string    `json:"lastModifiedBy"`
			LastModifiedDate          time.Time `json:"lastModifiedDate"`
			TransactionUUID           any       `json:"transactionUuid"`
			AuthenUsername            any       `json:"authenUsername"`
			SupplierID                any       `json:"supplierId"`
			CancelFileName            any       `json:"cancelFileName"`
			InvoiceType               string    `json:"invoiceType"`
			AdjustmentType            string    `json:"adjustmentType"`
			SupplierTaxCode           any       `json:"supplierTaxCode"`
			TemplateCode              string    `json:"templateCode"`
			Username                  any       `json:"username"`
			Password                  any       `json:"password"`
			BackOffice                any       `json:"backOffice"`
			IssueDate                 time.Time `json:"issueDate"`
			InvoiceSeri               string    `json:"invoiceSeri"`
			InvoiceNumber             int       `json:"invoiceNumber"`
			InvoiceNo                 string    `json:"invoiceNo"`
			BuyerIDType               string    `json:"buyerIdType"`
			BuyerIDTypeName           any       `json:"buyerIdTypeName"`
			BuyerIDNo                 string    `json:"buyerIdNo"`
			BuyerTaxCode              string    `json:"buyerTaxCode"`
			BuyerName                 string    `json:"buyerName"`
			BuyerAddress              string    `json:"buyerAddress"`
			BankName                  string    `json:"bankName"`
			BankAccount               string    `json:"bankAccount"`
			DeliveryOrder             any       `json:"deliveryOrder"`
			DeliveryWarehouse         any       `json:"deliveryWarehouse"`
			Warehouse                 any       `json:"warehouse"`
			DeliveryCarrier           any       `json:"deliveryCarrier"`
			DeliveryVehicle           any       `json:"deliveryVehicle"`
			ContractNo                string    `json:"contractNo"`
			TotalAmountWithoutVAT     float64   `json:"totalAmountWithoutVAT"`
			TotalVATAmount            float64   `json:"totalVATAmount"`
			DiscountAmount            float64   `json:"discountAmount"`
			TotalAmountWithVAT        float64   `json:"totalAmountWithVAT"`
			TotalAmountAfterDiscount  float64   `json:"totalAmountAfterDiscount"`
			TotalAmountWithVATFrn     any       `json:"totalAmountWithVATFrn"`
			TotalAmountWithVATInWords any       `json:"totalAmountWithVATInWords"`
			InvoiceListID             int       `json:"invoiceListId"`
			InvoicePath               any       `json:"invoicePath"`
			FolderID                  any       `json:"folderId"`
			FilePath                  any       `json:"filePath"`
			FileName                  string    `json:"fileName"`
			InstanceFilePath          any       `json:"instanceFilePath"`
			InstanceFileName          any       `json:"instanceFileName"`
			ExchangeFilePath          any       `json:"exchangeFilePath"`
			ExchangeFileName          any       `json:"exchangeFileName"`
			BackofficeRequestTime     any       `json:"backofficeRequestTime"`
			ResponseBackofficeTime    any       `json:"responseBackofficeTime"`
			LastUpdateTime            any       `json:"lastUpdateTime"`
			TempFilePath              any       `json:"tempFilePath"`
			TempFileName              any       `json:"tempFileName"`
			ErrorCode                 string    `json:"errorCode"`
			Description               any       `json:"description"`
			CurrencyCode              string    `json:"currencyCode"`
			ReservationCode           string    `json:"reservationCode"`
			SignatureValue            string    `json:"signatureValue"`
			DigestValue               any       `json:"digestValue"`
			CreateTime                any       `json:"createTime"`
			StateCode                 any       `json:"stateCode"`
			Status                    any       `json:"status"`
			NumOfUpdate               int       `json:"numOfUpdate"`
			PaymentStatus             int       `json:"paymentStatus"`
			ViewStatus                any       `json:"viewStatus"`
			BuyerViewStatus           int       `json:"buyerViewStatus"`
			DownloadStatus            any       `json:"downloadStatus"`
			BuyerDownloadStatus       any       `json:"buyerDownloadStatus"`
			ExchangeStatus            int       `json:"exchangeStatus"`
			InvoiceTemplateID         int       `json:"invoiceTemplateId"`
			NumOfExchange             any       `json:"numOfExchange"`
			ContractID                any       `json:"contractId"`
			OriginalInvoiceNo         any       `json:"originalInvoiceNo"`
			BuyerEmailAddress         string    `json:"buyerEmailAddress"`
			PaymentMethod             string    `json:"paymentMethod"`
			FeeType                   any       `json:"feeType"`
			BuyerUnitName             string    `json:"buyerUnitName"`
			PaymentTime               any       `json:"paymentTime"`
			ExchangeTime              any       `json:"exchangeTime"`
			CusGetInvoiceRight        any       `json:"cusGetInvoiceRight"`
			PaymentType               any       `json:"paymentType"`
			PaymentTypeName           any       `json:"paymentTypeName"`
			OriginalIssueDate         any       `json:"originalIssueDate"`
			InvoiceNote               any       `json:"invoiceNote"`
			ExchangeUser              any       `json:"exchangeUser"`
			PaymentMethodName         string    `json:"paymentMethodName"`
			CustomerID                any       `json:"customerId"`
			Domain                    any       `json:"domain"`
			ServiceType               any       `json:"serviceType"`
			ServiceTypeName           any       `json:"serviceTypeName"`
			NoCheckPaymentStatus      any       `json:"noCheckPaymentStatus"`
			ParentSupplierTaxCode     any       `json:"parentSupplierTaxCode"`
			TenantID                  any       `json:"tenantId"`
			AutoCreatePdfInstance     int       `json:"autoCreatePdfInstance"`
			TenantTaxCode             string    `json:"tenantTaxCode"`
			CreateUser                any       `json:"createUser"`
			BuyerPhoneNumber          string    `json:"buyerPhoneNumber"`
			InvoiceTypeID             int       `json:"invoiceTypeId"`
			AdditionalReferenceDesc   any       `json:"additionalReferenceDesc"`
			AdditionalReferenceDate   any       `json:"additionalReferenceDate"`
			BuyerLegalName            any       `json:"buyerLegalName"`
			AdjustmentInvoiceType     any       `json:"adjustmentInvoiceType"`
			AdjustedStatus            int       `json:"adjustedStatus"`
			NumOfAdjusted             any       `json:"numOfAdjusted"`
			TaxDeclarationStatus      int       `json:"taxDeclarationStatus"`
			InvoiceRequestID          any       `json:"invoiceRequestId"`
			TransactionID             string    `json:"transactionId"`
			BuyerCode                 string    `json:"buyerCode"`
			BuyerSigned               int       `json:"buyerSigned"`
			AgreementFilePath         any       `json:"agreementFilePath"`
			AgreementFileName         any       `json:"agreementFileName"`
			SpecificationFilePath     any       `json:"specificationFilePath"`
			SpecificationFileName     any       `json:"specificationFileName"`
			KeepInvoiceNo             any       `json:"keepInvoiceNo"`
			InvoiceStatus             int       `json:"invoiceStatus"`
			InvoiceTemplateFile       any       `json:"invoiceTemplateFile"`
			InvoiceFileXML            any       `json:"invoiceFileXml"`
			ProcessStatus             int       `json:"processStatus"`
			ListProduct               string    `json:"listProduct"`
			ListInfoUpdate            string    `json:"listInfoUpdate"`
			InvoiceTemplateName       any       `json:"invoiceTemplateName"`
			ProductLst                any       `json:"productLst"`
			ExchangeRate              float64   `json:"exchangeRate"`
			ListElectricityWater      any       `json:"listElectricityWater"`
			ReasonRecovery            any       `json:"reasonRecovery"`
			IndexStr                  any       `json:"indexStr"`
			HospitalDataDTO           any       `json:"hospitalDataDTO"`
			LstProduct                any       `json:"lstProduct"`
			TaxPolicy                 any       `json:"taxPolicy"`
			DiscountPolicy            any       `json:"discountPolicy"`
			IssueDateStr              any       `json:"issueDateStr"`
			CustomerCode              any       `json:"customerCode"`
			ParentTenantTaxCode       any       `json:"parentTenantTaxCode"`
			TypeSigined               any       `json:"typeSigined"`
			HashCode                  any       `json:"hashCode"`
			TenantBranchID            int       `json:"tenantBranchId"`
			SignatureType             any       `json:"signatureType"`
			ActionInvoiceDTO          struct {
				AdjustInfo       int `json:"adjustInfo"`
				AdjustMoney      int `json:"adjustMoney"`
				Replace          int `json:"replace"`
				Delete           int `json:"delete"`
				Exchange         int `json:"exchange"`
				SendEmail        int `json:"sendEmail"`
				SendSMS          int `json:"sendSMS"`
				Pay              int `json:"pay"`
				DownloadExchange int `json:"downloadExchange"`
				Restore          int `json:"restore"`
			} `json:"actionInvoiceDTO"`
			IsAction                  int    `json:"isAction"`
			CertString                any    `json:"certString"`
			Serial                    any    `json:"serial"`
			HashValue                 any    `json:"hashValue"`
			IsFile                    int    `json:"isFile"`
			SellerInfo                any    `json:"sellerInfo"`
			HasSeller                 any    `json:"hasSeller"`
			ErrorDescription          any    `json:"errorDescription"`
			ReasonDelete              any    `json:"reasonDelete"`
			IssueDateSTR              any    `json:"issueDateSTR"`
			AdjustSTR                 any    `json:"adjustSTR"`
			ImportFileID              int    `json:"importFileId"`
			TotalScan                 any    `json:"totalScan"`
			RemainScan                any    `json:"remainScan"`
			StartDateQrcode           any    `json:"startDateQrcode"`
			EndDateQrcode             any    `json:"endDateQrcode"`
			BuyerEmailReceiverOther   any    `json:"buyerEmailReceiverOther"`
			UserRelease               string `json:"userRelease"`
			CreateName                any    `json:"createName"`
			IssueName                 any    `json:"issueName"`
			TotalExciseTaxAmount      any    `json:"totalExciseTaxAmount"`
			TotalServiceChargeAmount  any    `json:"totalServiceChargeAmount"`
			ManyProductOfInvoice      any    `json:"manyProductOfInvoice"`
			TypeID                    any    `json:"typeId"`
			TypeName                  any    `json:"typeName"`
			ClassifyID                any    `json:"classifyId"`
			ClassifyName              any    `json:"classifyName"`
			TypeStatus                any    `json:"typeStatus"`
			TypeTax                   any    `json:"typeTax"`
			StatusMistakeReport       any    `json:"statusMistakeReport"`
			TotalAmountBeforeDiscount any    `json:"totalAmountBeforeDiscount"`
			SignCAErr                 bool   `json:"signCAErr"`
		} `json:"content"`
		Pageable struct {
			Sort struct {
				Unsorted bool `json:"unsorted"`
				Sorted   bool `json:"sorted"`
				Empty    bool `json:"empty"`
			} `json:"sort"`
			PageNumber int  `json:"pageNumber"`
			PageSize   int  `json:"pageSize"`
			Offset     int  `json:"offset"`
			Paged      bool `json:"paged"`
			Unpaged    bool `json:"unpaged"`
		} `json:"pageable"`
		TotalPages    int  `json:"totalPages"`
		TotalElements int  `json:"totalElements"`
		Last          bool `json:"last"`
		Sort          struct {
			Unsorted bool `json:"unsorted"`
			Sorted   bool `json:"sorted"`
			Empty    bool `json:"empty"`
		} `json:"sort"`
		NumberOfElements int  `json:"numberOfElements"`
		First            bool `json:"first"`
		Size             int  `json:"size"`
		Number           int  `json:"number"`
		Empty            bool `json:"empty"`
	} `json:"data"`
	ErrorCode any `json:"errorCode"`
}
